name: Deploy Flask Webhook App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Stop and remove old container if exists
            docker stop webhook || true
            docker rm webhook || true

            # Clone or pull the latest code
            if [ ! -d "webhook-flask-app" ]; then
              git clone https://github.com/hariprasathudayakumar808/webhook-flask-app.git
            fi

            cd webhook-flask-app
            git pull origin main

            # Build and run Docker container
            docker build -t webhook-flask-app .
            docker run -d -p 5000:5000 --name webhook webhook-flask-app
          EOF
