name: SSH Test

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Decode SSH private key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Try SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo '✅ SSH SUCCESS'"
